name: Marco Lopes TV
description: Marco Lopes's videos
url: 'https://marco-lopes.tv'
baseurl: ''
email: marco at mlop dot es
twitter: https://twitter.com/mpmlopes
youtube: https://www.youtube.com/user/mpmlopes

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video